[repository]
  name = "hyprstretch"
  authors = ["Rommmmaha"]
  commit_pins = [
    # ["<Hyprland-commit-hash>", "<Plugin-commit-hash>"]
    ["efb50993780079460b0cbed1363e2166a2de1d9f", "1e6c14e0d4ea3a4263219abc8fff5bf070b3d2f7"],
  ]

[hyprstretch]
  description = "Resize windows without changing their resolution"
  authors = ["Rommmmaha"]
  output = "hyprstretch/hyprstretch.so"
  build = ["make -C hyprstretch"]
